export const MODE_CHANGED = 'MODE_CHANGED';

export const IMAGE_CHANGED = 'IMAGE_CHANGED';

export const IMAGE_LOADED = 'IMAGE_LOADED';

export const TEXTAREA_CHANGED = 'TEXTAREA_CHANGED';

export const COLOR_CHANGED = 'COLOR_CHANGED';

export const OPACITY_CHANGED = 'OPACITY_CHANGED';

export const SHOW_APP_NAME_CHANGED = 'SHOW_APP_NAME_CHANGED';

export const FORCE_RENDER = 'FORCE_RENDER';
